[FIX] Use pytorch-lightning instead of lightning
Fixes:
```
ModuleNotFoundError: No module named 'pytorch_lightning'
```

Also, clean up the cache of apt and pip